// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNa_LsCc7FWYDpxwRhoGsc_HGtZoVfBg',
    appId: '1:482741233322:web:6790380f13da8087afd2d3',
    messagingSenderId: '482741233322',
    projectId: 'mynotes-second-proj',
    authDomain: 'mynotes-second-proj.firebaseapp.com',
    storageBucket: 'mynotes-second-proj.appspot.com',
    measurementId: 'G-M2JFFDCK57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA84Su0F73-JuUKALglfEcInVR7BizbvIY',
    appId: '1:482741233322:android:d516426c74460e74afd2d3',
    messagingSenderId: '482741233322',
    projectId: 'mynotes-second-proj',
    storageBucket: 'mynotes-second-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tR6ss0f76Lv2_aTjMxwz__NOOKl7p7k',
    appId: '1:482741233322:ios:8c91064d15769097afd2d3',
    messagingSenderId: '482741233322',
    projectId: 'mynotes-second-proj',
    storageBucket: 'mynotes-second-proj.appspot.com',
    iosClientId: '482741233322-e4v36nda71t35vhpolgnl0tjpk4qnp8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7tR6ss0f76Lv2_aTjMxwz__NOOKl7p7k',
    appId: '1:482741233322:ios:4aa10f61dde5f4ffafd2d3',
    messagingSenderId: '482741233322',
    projectId: 'mynotes-second-proj',
    storageBucket: 'mynotes-second-proj.appspot.com',
    iosClientId: '482741233322-t04g6cu0nd20796jqedkakdf2783uorn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
